#!/usr/bin/env python3
"""Option (b): translate the moat default policy into the host's own sandbox config.

  gen_host_config.py codex  --project DIR   > $CODEX_HOME/config.toml
  gen_host_config.py claude --project DIR   > $CLAUDE_CONFIG_DIR/settings.json

Key names were read from the installed binaries (codex-cli 0.160.0, Claude Code 2.1.290);
see README.md "Q4". Every lossy step is marked LOSSY below and in the README table.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_profile import DEFAULT_POLICY, load_policy, rule, split  # noqa: E402


def policy_parts(policy):
    secrets, secret_exceptions = split(rule(policy, "deny", "secrets-paths")["fs.read"])
    no_write = rule(policy, "deny", "kernel-self")["fs.write"] + rule(policy, "deny", "shell-rc")["fs.write"]
    # LOSSY: kernel-self denies writing the directory node itself (`**/.claude`: no rename or
    # delete) separately from its files. Both hosts treat a directory path as its whole
    # subtree, which would make every `.claude/worktrees/*` checkout read-only (verified),
    # so a bare directory that has more specific entries below it is left out.
    no_write = [p for p in no_write if not any(q.startswith(p + "/") for q in no_write)]
    return {
        "secrets": secrets,
        "secret_exceptions": secret_exceptions,
        "no_write": no_write,
        "hosts": rule(policy, "allow", "registries")["net"],
        "net_deny": [h for r in policy["deny"] for h in r.get("net", [])],
    }


def anchor(p, project):
    """Codex paths must be absolute, `~/...` or `:special`. LOSSY: `**/x` (anywhere on disk)
    can only be expressed under a known root, so it is anchored to the project."""
    if p.startswith("**/"):
        return f"{project}/{p}"
    return p.replace("${project}", project)


def codex(parts, project):
    fs = {}
    for p in parts["secrets"]:
        fs[anchor(p, project)] = "deny"            # "deny" blocks read and write
    for p in parts["no_write"]:
        # LOSSY: Codex globs support only `deny`, so a read-only `**/x` becomes `<project>/x`
        # (nested copies of x stay writable) and other read-only globs are dropped
        q = (f"{project}/{p[3:]}" if p.startswith("**/") else anchor(p, project)).removesuffix("/**")
        if "*" in q:
            continue
        fs.setdefault(q, "read")  # read-only; a secret deny already set wins
    lines = [
        "# generated by spikes/sandbox/gen_host_config.py from the moat default policy",
        'default_permissions = "moat"',
        'approval_policy = "on-request"',
        "",
        "[permissions.moat]",
        'extends = ":workspace"   # project roots + temp writable, reads elsewhere',
        "",
        "[permissions.moat.filesystem]",
        *(f"{json.dumps(k)} = {json.dumps(v)}" for k, v in fs.items()),
        "",
        "[permissions.moat.network]",
        "enabled = true          # direct network stays blocked; the Codex proxy filters by domain",
        "",
        "[permissions.moat.network.domains]",
        *(f'{json.dumps(h)} = "allow"' for h in parts["hosts"]),
        # LOSSY: IP globs (169.254.*) have no domain form; unlisted hosts are denied anyway
        *(f'{json.dumps(h)} = "deny"' for h in parts["net_deny"] if "*" not in h),
        "",
        "[features]",
        "network_proxy = true",
    ]
    return "\n".join(lines) + "\n"


def claude(parts, project):
    # A relative path in user settings resolves against ~/.claude, so `**/.env` would only
    # cover ~/.claude/**/.env (verified: it leaks the project's .env). Anchor it at `/`.
    rel = lambda p: ("/" + p if p.startswith("**/") else p).replace("${project}", project)
    return json.dumps({
        "sandbox": {
            "enabled": True,
            "failIfUnavailable": True,          # default false = run unsandboxed with a warning
            "allowUnsandboxedCommands": False,  # default true = model may set dangerouslyDisableSandbox
            "excludedCommands": [],
            "filesystem": {
                "denyRead": [rel(p) for p in parts["secrets"]],
                "allowRead": [rel(p) for p in parts["secret_exceptions"]],
                "denyWrite": [rel(p) for p in parts["secrets"] + parts["no_write"]],
            },
            "network": {
                "allowedDomains": parts["hosts"],
                "deniedDomains": [h for h in parts["net_deny"] if "*" not in h],
                "strictAllowlist": True,        # deny unlisted hosts instead of prompting
            },
        },
    }, indent=2) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("host", choices=["codex", "claude"])
    ap.add_argument("--project", required=True)
    ap.add_argument("--policy", default=DEFAULT_POLICY)
    a = ap.parse_args()
    parts = policy_parts(load_policy(a.policy))
    project = os.path.realpath(a.project)
    sys.stdout.write((codex if a.host == "codex" else claude)(parts, project))


if __name__ == "__main__":
    main()
