//! Lightweight tier on macOS: a Seatbelt (SBPL) profile around the whole
//! agent, generated from the IR of one session (ADR-018).
//!
//! What the generator relies on, verified with `sandbox-exec` on macOS 26:
//! - the last matching rule wins, so the policy's deny rules come last and no
//!   allow above them can re-open what they name (ADR-002);
//! - a read deny of `file-read-data` (contents) and `file-read-xattr` leaves
//!   `stat` working, so `git status` does not fail on `.env`;
//! - `require-all`/`require-not` express a rule's `!` exceptions exactly;
//! - paths are compared resolved (`/tmp` is `/private/tmp`) and in their
//!   on-disk spelling, even when a program names them in another case;
//! - a program cannot start from a file it cannot read, and the dynamic loader
//!   needs to read `/` itself;
//! - a network address can only be `*` or `localhost`, so egress goes to the
//!   loopback port of moat's proxy, which decides each host by the policy.

use std::fmt::Write as _;

use moat_core::Kind;
use moat_core::ir::{Access, Effect, Enforcement, Rule};

use super::Report;
use super::patterns::{literal_tree, split};

/// Paths every process reads: `/` (the dynamic loader), the terminal and
/// random devices, and `/private/var/select` (where `/bin/sh` finds its shell).
const PLATFORM_READ: [&str; 9] = [
    "/",
    "/dev/null",
    "/dev/zero",
    "/dev/random",
    "/dev/urandom",
    "/dev/tty",
    "/dev/ttys[0-9]*",
    "/dev/fd/**",
    "/private/var/select/**",
];

/// Devices every process writes.
const PLATFORM_WRITE: [&str; 6] = [
    "/dev/null",
    "/dev/zero",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/ttys[0-9]*",
    "/dev/fd/**",
];

/// What every process may do besides files: start programs, signal and
/// inspect its own processes, use terminals and shared memory, and look up
/// users and groups. No other system service: not the keychain
/// (`SecurityServer`), not DNS (the proxy resolves), not `trustd`, which
/// fetches certificate status from the network.
const PROCESS: &str = "\
(allow process-exec process-fork)
(allow signal (target same-sandbox))
(allow process-info* (target same-sandbox))
(allow sysctl-read)
(allow pseudo-tty)
(allow file-ioctl)
(allow ipc-posix-shm* ipc-posix-sem)
(allow mach-lookup
  (global-name \"com.apple.system.opendirectoryd.libinfo\")
  (global-name \"com.apple.system.opendirectoryd.membership\"))
";

/// The keychain's services, denied whatever the policy says: the agent and
/// every script it starts share this profile, so a token the agent could read
/// from the keychain, a project script could send away.
const KEYCHAIN: &str = "\
; never the keychain: the agent and its scripts share this profile
(deny mach-lookup
  (global-name \"com.apple.SecurityServer\")
  (global-name \"com.apple.securityd\"))
";

/// What the session adds to the IR.
#[derive(Debug, Clone, Default)]
pub struct Grants {
    /// The loopback port of moat's egress proxy, the only network destination.
    pub proxy_port: Option<u16>,
    /// The temp directory, resolved, which commands may read and write.
    pub tmpdir: Option<String>,
}

/// A generated profile.
#[derive(Debug, Clone)]
pub struct Generated {
    /// The SBPL text `sandbox-exec -p` takes.
    pub profile: String,
    /// Losses and allowances of this backend.
    pub report: Report,
}

/// Generate the profile for `ir`, lowered for one session's project.
pub fn generate(ir: &Enforcement, grants: &Grants) -> Generated {
    let mut report = Report::default();
    let mut out = String::from(
        "(version 1)\n\
         ; generated by moat from policy.yaml for `moat run` (Lightweight tier, ADR-018)\n\
         (deny default)\n",
    );
    out.push_str(PROCESS);
    out.push_str("; seatbelt.metadata\n(allow file-read-metadata)\n");
    report.allowance(
        Kind::FsRead,
        "seatbelt.metadata",
        Vec::new(),
        "the existence, size and times of every file stay visible (stat); contents follow the rules",
    );
    let platform = |list: &[&str]| list.iter().map(|p| (*p).to_owned()).collect::<Vec<_>>();
    rule(
        &mut out,
        "seatbelt.platform",
        "allow file-read*",
        &platform(&PLATFORM_READ),
    );
    rule(
        &mut out,
        "seatbelt.platform",
        "allow file-write-data",
        &platform(&PLATFORM_WRITE),
    );
    report.allowance(
        Kind::FsRead,
        "seatbelt.platform",
        platform(&PLATFORM_READ),
        "every process reads these to start",
    );
    report.allowance(
        Kind::FsWrite,
        "seatbelt.platform",
        platform(&PLATFORM_WRITE),
        "the devices every process writes",
    );
    allows(&mut out, &ir.fs.read, "allow file-read*");
    for allowance in &ir.allowances {
        rule(
            &mut out,
            &allowance.rule,
            "allow file-read*",
            &allowance.patterns,
        );
        report.allowances.push(allowance.clone());
    }
    allows(&mut out, &ir.fs.write, "allow file-write*");
    if let Some(tmpdir) = &grants.tmpdir {
        let tree = vec![format!("{tmpdir}/**")];
        rule(
            &mut out,
            "seatbelt.tmpdir",
            "allow file-read* file-write*",
            &tree,
        );
        report.allowance(
            Kind::FsWrite,
            "seatbelt.tmpdir",
            tree,
            "commands may read and write the temp directory; the hook asks",
        );
    }
    rules(
        &mut out,
        &ir.fs.read.deny,
        "deny file-read-data file-read-xattr",
    );
    rules(&mut out, &ir.fs.write.deny, "deny file-write*");
    out.push_str(KEYCHAIN);
    network(&mut out, &ir.egress.net, grants.proxy_port, &mut report);
    if ir.fs.case_insensitive {
        report.allowance(
            Kind::FsRead,
            "seatbelt.case",
            Vec::new(),
            "Seatbelt compares paths in their on-disk spelling, so a pattern spelled in another \
             case than the file on disk does not match it",
        );
    }
    Generated {
        profile: out,
        report,
    }
}

/// The access's default, then its allow rules.
fn allows(out: &mut String, access: &Access, operation: &str) {
    if access.default == Effect::Allow {
        let _ = writeln!(out, "; default\n({operation})");
    }
    rules(out, &access.allow, operation);
}

/// One `(<operation> …)` per IR rule, named in a comment.
fn rules(out: &mut String, rules: &[Rule], operation: &str) {
    let verb = operation.split(' ').next().unwrap_or_default();
    for r in rules {
        let comment = format!("{verb} {} ({})", r.id, r.list);
        rule(out, &comment, operation, &r.patterns);
    }
}

/// `(<operation> …)` matching what `patterns` match: at least one positive
/// pattern and none of the `!` exceptions.
fn rule(out: &mut String, comment: &str, operation: &str, patterns: &[String]) {
    let (mut positive, excluded) = split(patterns);
    // `dir/**` becomes `(subpath dir)`, which covers `dir` itself.
    positive.retain(|p| !patterns.contains(&format!("{p}/**")));
    if positive.is_empty() {
        return;
    }
    let lines = |list: &[&str], indent: &str| {
        let filters: Vec<String> = list.iter().map(|p| filter(p)).collect();
        format!("\n{indent}{}", filters.join(&format!("\n{indent}")))
    };
    let _ = write!(out, "; {comment}\n({operation}");
    if excluded.is_empty() {
        out.push_str(&lines(&positive, "  "));
    } else {
        let _ = write!(
            out,
            "\n  (require-all\n    (require-any{})\n    (require-not (require-any{})))",
            lines(&positive, "      "),
            lines(&excluded, "      ")
        );
    }
    out.push_str(")\n");
}

/// Egress goes only to the proxy's loopback port: Seatbelt cannot name a host.
fn network(out: &mut String, net: &Access, port: Option<u16>, report: &mut Report) {
    match port {
        Some(port) => {
            let _ = writeln!(
                out,
                "; network: only moat's egress proxy, which decides each host by the policy\n\
                 (allow network-outbound (remote ip \"localhost:{port}\"))"
            );
        }
        None => out.push_str("; network: none\n"),
    }
    if net.default == Effect::Allow {
        report.loss(
            Kind::Net,
            "default.net",
            "every host is reachable only through moat's proxy".into(),
        );
    }
    for r in &net.allow {
        report.loss(
            Kind::Net,
            &r.id,
            "these hosts are reachable only through moat's proxy: a program that ignores \
             HTTP(S)_PROXY cannot reach them"
                .into(),
        );
    }
}

/// One IR glob as a Seatbelt path filter.
fn filter(pattern: &str) -> String {
    match literal_tree(pattern) {
        Some(dir) if pattern.ends_with("/**") => format!("(subpath {})", quote(dir)),
        Some(path) => format!("(literal {})", quote(path)),
        None => format!("(regex {})", quote(&regex(pattern))),
    }
}

/// An SBPL string literal.
fn quote(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}

/// A path glob as an anchored regular expression with the engine's semantics
/// (`docs/POLICY.md` §3): `*` and `?` stop at `/`, `**` as a whole component
/// crosses it, and `dir/**` also matches `dir`.
fn regex(glob: &str) -> String {
    let mut re = String::from("^");
    let mut depth = 0usize;
    let mut i = 0;
    while let Some(c) = glob[i..].chars().next() {
        let rest = &glob[i..];
        let (piece, used) = if rest == "/**" {
            ("(/.*)?".to_owned(), 3)
        } else if rest.starts_with("/**/") {
            ("/(.*/)?".to_owned(), 4)
        } else if i == 0 && rest == "**" {
            (".*".to_owned(), 2)
        } else if i == 0 && rest.starts_with("**/") {
            ("(.*/)?".to_owned(), 3)
        } else {
            match c {
                '*' => ("[^/]*".to_owned(), 1),
                '?' => ("[^/]".to_owned(), 1),
                '{' => {
                    depth += 1;
                    ("(".to_owned(), 1)
                }
                '}' if depth > 0 => {
                    depth -= 1;
                    (")".to_owned(), 1)
                }
                ',' if depth > 0 => ("|".to_owned(), 1),
                '[' => class(rest).unwrap_or_else(|| (escape('['), 1)),
                '\\' => match rest[1..].chars().next() {
                    Some(next) => (escape(next), 1 + next.len_utf8()),
                    None => (escape('\\'), 1),
                },
                other => (escape(other), other.len_utf8()),
            }
        };
        re.push_str(&piece);
        i += used;
    }
    re.push('$');
    re
}

/// A glob character class at the start of `rest` (`[ab]`, `[!ab]`) and its
/// length, or `None` when it is not closed.
fn class(rest: &str) -> Option<(String, usize)> {
    let body = &rest[1..];
    let (negated, body) = match body.strip_prefix(['!', '^']) {
        Some(b) => (true, b),
        None => (false, body),
    };
    // A `]` right after the opening bracket is a member, not the end.
    let end = body.char_indices().skip(1).find(|(_, c)| *c == ']')?.0;
    let members = body[..end].replace('\\', "\\\\");
    let negation = if negated { "^/" } else { "" };
    Some((
        format!("[{negation}{members}]"),
        rest.len() - body.len() + end + 1,
    ))
}

fn escape(c: char) -> String {
    if ".^$|()+[]{}\\*?".contains(c) {
        format!("\\{c}")
    } else {
        c.to_string()
    }
}

#[cfg(test)]
mod tests;
